TUNING.MIN_TIME_BETWEEN_FLICKER = 20
TUNING.MAX_TIME_BETWEEN_FLICKER = 30
TUNING.MIN_FLICKER_DURATION = 0.5
TUNING.MAX_FLICKER_DURATION = 2.5
TUNING.OFF_SUBFLICKER_TICKS = 6
TUNING.ON_SUBFLICKER_TICKS = 1
TUNING.FLICKER_DIM_AMOUNT = 0.5
TUNING.MIN_REASONABLE_FUEL = 0.12
TUNING.MIN_REASONABLE_BRIGHTNESS = 0.45
TUNING.LOW_FUEL_LEVEL = 100 --This is the value at which we start to consider the player to be in darkness while flashlight is on
TUNING.STARTING_FUEL_LEVEL = 3000 --How much fuel is in the battery the player starts with
TUNING.MAX_FUEL_LEVEL = 10000 --this is also how many tic

TUNING.SEARCH_CONTAINER_DURATION = 1.5

TUNING.MOUSE_SENSITIVITY = 0.15 --Was originally 1.5
TUNING.PITCH_ADJUSTMENT_MULTIPLIER = 5

TUNING.PITCH_ADDITIONAL_OFFSET = 0.2


TUNING.BLOOD_OVERLAY_VALUE_FOR_DEATH = 7.5
TUNING.DARKNESS_STALKTIME = 4.5
TUNING.DARKNESS_STALKTIME2 = 5

TUNING.IS_FPS = false
if TUNING.IS_FPS then
	TUNING.DEFAULT_CAM_DISTANCE = 8
	TUNING.ZOOMED_CAM_DISTANCE = 8
	TUNING.CAMERAY_OFFSET = 4.5
end

TUNING.SANITYAURA_MONSTER = 50
TUNING.DAPPERNESS_FREE = 2